version: '3'
services:
  langchain-streamlit-agent:
    image: langchain-streamlit-agent:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./streamlit_agent:/app/streamlit_agent
      - ./config:/app/config
    ports:
      - "8051:8051"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8051"]
      interval: 30s
      timeout: 10s
      retries: 3